["a", "b", "c"].length()
[1, 2, 3, 4, 5, 6].shuffle()
[1, 2, 3].push(4)
["a", "b", "c", "d", "e"].at(2)
["a", "b", "c", "d", "e"].at(0)
["e", "p", "i", "c", "o", "d", "u", "s"].join()
"i love music".split()
["lions", "tigers", "bears"].join(",")
"epicodus".split("")
(1..10).size()
("a".."z").end()
["this", "is", "my", "number", 1, "array"].unshift("awesome")
["this", "is", "my", "number", 1, "array"].shift()
["this", "is", "my", "number", 1, "array"].reverse()
["this", "is", "my", "number", 1, "array"].pop()
["this", "is", "my", "number", 1, "array"].join(" ")
["this", "is", "my", "number", 1, "array"].sample()
["this", "is", "my", "number", 1, "array", "again", "again", "again"].uniq()
["this", "is", "my", "number", 1, "array"].shuffle()
(1..20).size()
("c".."z").begin()
("c".."w").end()
