5.next()
5.3.round()
8.1.ceil()
5.3.round().next()
5.3.ceil().next()
"Hello world!".length()
"I love ice cream".upcase()
"denim".upcase().reverse()
2.3.class()
80.class()
"hello world".class()
"tango and bay".capitalize()
"TANGO AND BAY".downcase()
"tango".chop()
"tango".clear()
5.next()
5.pred()
4.45.ceil()
4.77.floor()
4.49.round()
